### ISSUE TITLE
Fix the doc, the base css is wrong

### ISSUE THREAD

**Issue by gabriel-dehan** [itemslide/itemslide.github.io#12]
The docs says that the needed base css is this one :

```css
ul {
    margin: 0;
    padding: 0;
    list-style-type: none;
    position: absolute;
    -webkit-transform-style: preserve-3d;
    -ms-transform-style: preserve-3d;
    transform-style: preserve-3d;
}

li {
    float: left;
}
```

Meanwhile this line https://github.com/itemslide/itemslide.github.io/blob/master/src/itemslide.js#L81, says otherwise.
You actually need to put at least `left: 0;` in your css otherwise initialLeft is `NaN` (because the default css value is `auto`) and therefore every calculation fails afterwards.

Took me a while to figure this one out, if you could update the doc to prevent somebody else running in the same issue it would be great :)
